### ISSUE TITLE
Exception stack traces not propagated in getCommonSuperClass

### ISSUE THREAD

**Issue by immibis** [squeek502/ASMHelper#1]
See https://github.com/squeek502/ASMHelper/blob/master/java/squeek/asmhelper/ObfRemappingClassWriter.java#L25

If an unexpected exception is caught, the exception is wrapped and propagated, but only the message is kept (not the stack trace).

This line should probably be:

```
throw new RuntimeException(e);
```

**Comment by squeek502** [comment]
Fair enough. The current implementation simply mirrors asm.objectweb.asm.ClassWriter.getCommonSuperClass

http://grepcode.com/file/repository.springsource.com/org.objectweb.asm/com.springsource.org.objectweb.asm/3.2.0/org/objectweb/asm/ClassWriter.java#1284
